version: "3"
services:
  frontend:
    build: frontend
    depends_on:
      - api
    tty: true
    volumes:
      - ./frontend/public:/frontend/public:cached,ro
      - ./frontend/src:/frontend/src:cached,ro
    ports:
      - "3000:3000"
    networks:
      - filestage-app

  api:
    build: backend
    depends_on:
      - database
    tty: true
    volumes:
      - ./backend/bin:/backend/bin:cached,ro
      - ./backend/src:/backend/src:cached,ro
    ports:
      - "3001:3001"
    networks:
      - filestage-app
    depends_on:
      - database

  database:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - filestage-app
networks:
  filestage-app:
    driver: bridge
